### PR TITLE
BREAKING: Bump API version to 20200513

### PR DESCRIPTION
**Pull request by nickylogan**
# Description

This PR updates the library to support wit.ai's latest API version. See #17.

# Pull Requests

Thanks for proposing a pull request.

To help us review the request, please complete the following:
- [x] sign contributor license agreement: https://developers.facebook.com/opensource/cla
- [x] submit against our `master`.
- [x] describe the change (for example, what happens before the change, and after the change)

### CODE REVIEW

**Comment by plutov** [comment]
@nickylogan thank you for the PR! It looks great, since it's a breaking one there are things we should consider:
- Have clear documentation in README on now to use new API version vs old one. Also, do we need to set API version in the client or we'll keep only one? I suggest keeping single API version without letting users change it, since our Go structs support one version only.
- Check integration tests
- Bump new semver (I'll do this after merge)

**Comment by nickylogan** [comment]
> Also, do we need to set API version in the client or we'll keep only one? I suggest keeping single API version without letting users change it, since our Go structs support one version only.

@plutov The old client has a way to set the version of the API. If that's the case, I shall remove it along with this PR.

**Comment by plutov** [comment]
Yes, please remove the option to set API version

**Comment by plutov** [comment]
Looks good, can you also please update the README file on how to init a client?

**Comment by nickylogan** [comment]
> Looks good, can you also please update the README file on how to init a client?

@plutov  Will definitely do. But there are still some more changes to be made. I'll update the README after all the code changes.

**Comment by nickylogan** [comment]
@plutov hmmm. This PR is not ready yet, integration tests didn't work because of docs mismatch with actual API behavior. Are you sure this is intended?

**Comment by els2520** [comment]
> # Description
> 
> 
> 
> This PR updates the library to support wit.ai's latest API version. See #17.
> 
> 
> 
> # Pull Requests
> 
> 
> 
> Thanks for proposing a pull request.
> 
> 
> 
> To help us review the request, please complete the following:
> 
> - [x] sign contributor license agreement: https://developers.facebook.com/opensource/cla
> 
> - [x] submit against our `master`.
> 
> - [x] describe the change (for example, what happens before the change, and after the change)

**Pull request merged**
